#!/usr/bin/env bash
#
# Turn a collection of markdown files into a website.

# TODO (Make this a proper script).

# Main pages
for page in src/pages/*.md; do
    out_file="${page/*\/}"
    pandoc -o "pages/${out_file/\.md}.html" --template "src/templates/post.html" --smart -- "$page"
done

# Sub pages
for page in src/pages/rice/*.md; do
    out_file="${page/*\/}"
    pandoc -o "pages/rice/${out_file/\.md}.html" --template "src/templates/post.html" --smart -- "$page"
done

# Sub pages
for page in src/*.md; do
    out_file="${page/*\/}"
    pandoc -o "${out_file/\.md}.html" --template "src/templates/post.html" --smart -- "$page"
done
