#!/usr/bin/env bash
#
# Turn a collection of markdown files into a website.

pandoc_cmd() {
    [[ "$1" ]] && mkdir -p "$1" || return

    for page in src/"$1"/*.md; do
        dir="${page/src}"
        printf "%s\n" "Generating .${dir/\.md}.html..."
        pandoc -o ".${dir/\.md}.html" --template "src/templates/post.html" --smart -- "$page"
    done
}

# Generate pages.
pandoc_cmd "pages"
pandoc_cmd "pages/rice"
pandoc_cmd "."
